# Generated by Django 4.0.4 on 2022-07-04 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro_website', '0003_proyecto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='imgaen',
            new_name='imagen',
        ),
    ]
