# Generated by Django 4.0.4 on 2022-07-04 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro_website', '0008_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
