# Generated by Django 4.0.4 on 2022-07-04 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro_website', '0010_post_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
