# Generated by Django 4.0.4 on 2022-07-04 20:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pro_website', '0012_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='likes',
            field=models.ManyToManyField(related_name='proyecto', to=settings.AUTH_USER_MODEL),
        ),
    ]
