# Generated by Django 4.0.4 on 2022-07-04 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro_website', '0013_proyecto_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='likes',
        ),
    ]
