# Generated by Django 4.0.4 on 2022-07-04 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro_website', '0014_remove_proyecto_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
