# Generated by Django 4.0.4 on 2022-07-04 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro_website', '0016_likebutton'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikeButton',
        ),
    ]
